# Generated by Django 4.2.4 on 2023-10-19 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("isbn_number", models.CharField(max_length=13)),
            ],
            options={
                "db_table": "book",
            },
        ),
        migrations.CreateModel(
            name="CompiledImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filtered_images", models.ImageField(upload_to="temp/")),
            ],
        ),
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x_coord",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(99),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="x_coord",
                    ),
                ),
                (
                    "y_coord",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(39),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="y_coord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawMedidata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.CharField(max_length=50, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("2", "Male"), ("1", "Female"), ("3", "Other")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("1", "White"),
                            ("2", "Black"),
                            ("3", "Asian"),
                            ("4", "Native Hawaiian or Other Pacific Islander"),
                            ("5", "American Indian or Alaskan Native"),
                            ("6", "More than one race"),
                            ("7", "Other"),
                            ("8", "Unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("1", "18-25"),
                            ("2", "26-30"),
                            ("3", "31-35"),
                            ("4", "36-40"),
                            ("5", "41-45"),
                            ("6", "46-50"),
                            ("7", "51-55"),
                            ("8", "56-60"),
                            ("9", "61-65"),
                            ("10", "65-70"),
                            ("11", "71-75"),
                            ("12", ">75"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bmi",
                    models.CharField(
                        choices=[
                            ("1", "<18.5"),
                            ("2", "18.5-25"),
                            ("3", "25-30"),
                            ("4", ">30"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("heatmap", models.ImageField(upload_to="heatmaps_indexed/")),
            ],
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("2", "Male"), ("1", "Female"), ("3", "Other")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("1", "White"),
                            ("2", "Black"),
                            ("3", "Asian"),
                            ("4", "Native Hawaiian or Other Pacific Islander"),
                            ("5", "American Indian or Alaskan Native"),
                            ("6", "More than one race"),
                            ("7", "Other"),
                            ("8", "Unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("1", "18-25"),
                            ("2", "26-30"),
                            ("3", "31-35"),
                            ("4", "36-40"),
                            ("5", "41-45"),
                            ("6", "46-50"),
                            ("7", "51-55"),
                            ("8", "56-60"),
                            ("9", "61-65"),
                            ("10", "65-70"),
                            ("11", "71-75"),
                            ("12", ">75"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bmi",
                    models.CharField(
                        choices=[
                            ("1", "<18.5"),
                            ("2", "18.5-25"),
                            ("3", "25-30"),
                            ("4", ">30"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
